### PR TITLE
add sigs for v0.1.2

### PR DESCRIPTION
**Pull request by xanimo**
Opening for comparison of gitian build hashes relative to libdogecoin v0.1.2. Here are my hashes for release files:
```
dfe1476dd5bf64dc0c54a9e9a62c4b49b45575e05de529df2813ddbdf007e57a  libdogecoin-0.1.2-x86_64-apple-darwin14.tar.gz
90242d1059c689b8d3cc7439b5a4386b8025bb86fbb834f53191eaf268351f8e  libdogecoin-0.1.2-aarch64-linux-gnu.tar.gz
df8c56bd54a2e403f4807ec4b58daab7709c94f0d8f04ab84818415a87d97630  libdogecoin-0.1.2-arm-linux-gnueabihf.tar.gz
9a7add6775b6e8920d18de089036cdfa25ec3de1b57f7f82988663f695669c96  libdogecoin-0.1.2-i686-pc-linux-gnu.tar.gz
dfe1476dd5bf64dc0c54a9e9a62c4b49b45575e05de529df2813ddbdf007e57a  libdogecoin-0.1.2-x86_64-apple-darwin14.tar.gz
5622679e4fe40aa5602a93d84b9650c19b56d1579a9feb0ad5db0a95fcba8311  libdogecoin-0.1.2-x86_64-pc-linux-gnu.tar.gz
a3414014300beb548df53d3874c09dd883799ce05492129a06e31993fcb7a613  libdogecoin-0.1.2.tar.gz
b7af3ae84c493ea8b12ed270e2c3f7d32f9c8c8ae8d1ab8e76db80eeff8c5e6a  libdogecoin-0.1.2-i686-w64-mingw32.zip
bf5362e5b99a660a03d0025219cc90b27e68d8e80e0289353b31a665fa4debb2  libdogecoin-0.1.2-x86_64-w64-mingw32.zip
5297b3066e887f238279af6d8028475931d8e402431f01ccbc905359e969d1f7  libdogecoin-0.1.2.zip
```

### CODE REVIEW

**Comment by edtubbs** [comment]
```
90242d1059c689b8d3cc7439b5a4386b8025bb86fbb834f53191eaf268351f8e  libdogecoin-0.1.2-aarch64-linux-gnu.tar.gz
df8c56bd54a2e403f4807ec4b58daab7709c94f0d8f04ab84818415a87d97630  libdogecoin-0.1.2-arm-linux-gnueabihf.tar.gz
9a7add6775b6e8920d18de089036cdfa25ec3de1b57f7f82988663f695669c96  libdogecoin-0.1.2-i686-pc-linux-gnu.tar.gz
dfe1476dd5bf64dc0c54a9e9a62c4b49b45575e05de529df2813ddbdf007e57a  libdogecoin-0.1.2-x86_64-apple-darwin14.tar.gz
5622679e4fe40aa5602a93d84b9650c19b56d1579a9feb0ad5db0a95fcba8311  libdogecoin-0.1.2-x86_64-pc-linux-gnu.tar.gz
a3414014300beb548df53d3874c09dd883799ce05492129a06e31993fcb7a613  libdogecoin-0.1.2.tar.gz
b7af3ae84c493ea8b12ed270e2c3f7d32f9c8c8ae8d1ab8e76db80eeff8c5e6a  libdogecoin-0.1.2-i686-w64-mingw32.zip
bf5362e5b99a660a03d0025219cc90b27e68d8e80e0289353b31a665fa4debb2  libdogecoin-0.1.2-x86_64-w64-mingw32.zip
5297b3066e887f238279af6d8028475931d8e402431f01ccbc905359e969d1f7  libdogecoin-0.1.2.zip
```

**Comment by xanimo** [comment]
Here are new hashes per modifications to release:
```
95806283d10ef17feeea5820fa5987e6416a847bd23362b17a71357a2e547897  libdogecoin-0.1.2-aarch64-linux-gnu.tar.gz
566202859e708c55a9101e1e8a9e6f20ab970fd14a3b4ac97fe3ed132c69ca0c  libdogecoin-0.1.2-arm-linux-gnueabihf.tar.gz
de8855f6797225c2382424b022e729868fcfad36dff91954a7c0468726669919  libdogecoin-0.1.2-i686-pc-linux-gnu.tar.gz
f578f5754a89b06282fa8a73ae33d9edabcace69ebb11a0a60d4f57878e50ad8  libdogecoin-0.1.2-x86_64-apple-darwin14.tar.gz
da3cd0b3d9a8f4e86e586534b5f6c69f33c1f93b6f0ada6cc67822bd1dfb504b  libdogecoin-0.1.2-x86_64-pc-linux-gnu.tar.gz
7f0f2b3bda3ed5e22a6366588dbb4d5261fb0f9f81e6ac3ed29b3278f582659e  libdogecoin-0.1.2.tar.gz
04fd3f2bad86c2366ea03a4875221e60691f734b23b1fefa749121d82016714e  libdogecoin-0.1.2-i686-w64-mingw32.zip
4c4baa7d16e37d0db9c77d885a8895adf989e8e2e6a7f338508a7b69088db9f5  libdogecoin-0.1.2-x86_64-w64-mingw32.zip
e00b66a82f8b395ce27b68ad69f2a1019bf1f55c8b967f8c95a5cf4be7a97fac  libdogecoin-0.1.2.zip
```

**Comment by edtubbs** [comment]
```ed@ed-VirtualBox:~/dogecoin/foundation/libdogecoin/contrib/gitian/builds/v0.1.2$ cat checksums.txt 
95806283d10ef17feeea5820fa5987e6416a847bd23362b17a71357a2e547897  libdogecoin-0.1.2-aarch64-linux-gnu.tar.gz
566202859e708c55a9101e1e8a9e6f20ab970fd14a3b4ac97fe3ed132c69ca0c  libdogecoin-0.1.2-arm-linux-gnueabihf.tar.gz
de8855f6797225c2382424b022e729868fcfad36dff91954a7c0468726669919  libdogecoin-0.1.2-i686-pc-linux-gnu.tar.gz
f578f5754a89b06282fa8a73ae33d9edabcace69ebb11a0a60d4f57878e50ad8  libdogecoin-0.1.2-x86_64-apple-darwin14.tar.gz
da3cd0b3d9a8f4e86e586534b5f6c69f33c1f93b6f0ada6cc67822bd1dfb504b  libdogecoin-0.1.2-x86_64-pc-linux-gnu.tar.gz
7f0f2b3bda3ed5e22a6366588dbb4d5261fb0f9f81e6ac3ed29b3278f582659e  libdogecoin-0.1.2.tar.gz
04fd3f2bad86c2366ea03a4875221e60691f734b23b1fefa749121d82016714e  libdogecoin-0.1.2-i686-w64-mingw32.zip
4c4baa7d16e37d0db9c77d885a8895adf989e8e2e6a7f338508a7b69088db9f5  libdogecoin-0.1.2-x86_64-w64-mingw32.zip
e00b66a82f8b395ce27b68ad69f2a1019bf1f55c8b967f8c95a5cf4be7a97fac  libdogecoin-0.1.2.zip
```

**Review by edtubbs — APPROVED** [review]

**Comment by xanimo** [comment]
New sigs per last and final release :crossed_fingers: 
```
c3c6ec063f0509d9f76ed1d7c4e06f99808c642588bfd024a8704d32a75c0e18  libdogecoin-0.1.2-aarch64-linux-gnu.tar.gz
b7ef6c4254a9bed1aaaef4f3d8963e4aafe54ea2e72d666f1a05f32b1008c42e  libdogecoin-0.1.2-arm-linux-gnueabihf.tar.gz
95ffbf4e9d32ad05dd119f93340265c16f8b2f57aa805fdfb27a6fb7f354b904  libdogecoin-0.1.2-i686-pc-linux-gnu.tar.gz
ad71fbf07933e49c21c5811ccab20993d25e3621a3497a4ca7f155e8b793c763  libdogecoin-0.1.2-x86_64-apple-darwin14.tar.gz
165748dd29cea8d0c77447d38319346598fcc4df9238782b7786ed1cb30dff09  libdogecoin-0.1.2-x86_64-pc-linux-gnu.tar.gz
6f31e023ab5327733dedc9ebc7cc51bbfe86f026df49377274e799ba89c8be99  libdogecoin-0.1.2.tar.gz
9a67f7033c49ec6a8d03f39b68b578302ad393b62a150bb5b6dc9ea454d438b6  libdogecoin-0.1.2-i686-w64-mingw32.zip
5267f74e15514360ce9d3485873361a92497ff9a7237061324ba169545f343fb  libdogecoin-0.1.2-x86_64-w64-mingw32.zip
a9fe861e57abf64e3443c5b666da04fd131fcdae302696cca5b2d767605cdf5e  libdogecoin-0.1.2.zip
```

**Comment by edtubbs** [comment]
```
c3c6ec063f0509d9f76ed1d7c4e06f99808c642588bfd024a8704d32a75c0e18  libdogecoin-0.1.2-aarch64-linux-gnu.tar.gz
b7ef6c4254a9bed1aaaef4f3d8963e4aafe54ea2e72d666f1a05f32b1008c42e  libdogecoin-0.1.2-arm-linux-gnueabihf.tar.gz
95ffbf4e9d32ad05dd119f93340265c16f8b2f57aa805fdfb27a6fb7f354b904  libdogecoin-0.1.2-i686-pc-linux-gnu.tar.gz
ad71fbf07933e49c21c5811ccab20993d25e3621a3497a4ca7f155e8b793c763  libdogecoin-0.1.2-x86_64-apple-darwin14.tar.gz
165748dd29cea8d0c77447d38319346598fcc4df9238782b7786ed1cb30dff09  libdogecoin-0.1.2-x86_64-pc-linux-gnu.tar.gz
6f31e023ab5327733dedc9ebc7cc51bbfe86f026df49377274e799ba89c8be99  libdogecoin-0.1.2.tar.gz
9a67f7033c49ec6a8d03f39b68b578302ad393b62a150bb5b6dc9ea454d438b6  libdogecoin-0.1.2-i686-w64-mingw32.zip
5267f74e15514360ce9d3485873361a92497ff9a7237061324ba169545f343fb  libdogecoin-0.1.2-x86_64-w64-mingw32.zip
a9fe861e57abf64e3443c5b666da04fd131fcdae302696cca5b2d767605cdf5e  libdogecoin-0.1.2.zip
```

**Pull request merged**
